/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/Duck.h"
//#include <iostream>
#include <string.h>

#ifdef FEEDBACK_TEST_06
// Initial Test for Rubber Duck.  YayYay
TEST(MallardTest,Constructor){
  Duck* my_ralph = new Mallard();
  QuackBehavior* m = new Mute() ;
  FlyBehavior* f = new NoFly();
  string except_fly_perform_str="Fly with wings at speed of 5 mph.";
  string except_quack_perform_str = "Quack at 10 decibels.";
  string except_fly_set_str="Cannot fly.";
  string except_quack_set_str = "Cannot talk.";


  EXPECT_STREQ( except_fly_perform_str.c_str(),my_ralph->performFly().c_str()) << "FAIL: Mallard performFly function" ;
  EXPECT_STREQ( except_quack_perform_str.c_str(),my_ralph->performQuack().c_str()) << "FAIL: Mallard performQuack function" ;
  my_ralph->setFlyBehavior(f);
  my_ralph->setQuackBehavior(m);
  EXPECT_STREQ( except_fly_set_str.c_str(),my_ralph->performFly().c_str()) << "FAIL: Mallard: Duck setFly function" ;
  EXPECT_STREQ( except_quack_set_str.c_str(),my_ralph->performQuack().c_str()) << "FAIL: Mallard: Duck  setquack function" ;
}


TEST(MallardTest,display){
  Duck* my_ralph = new Mallard();
  string except_str="I am a Mallard.";
  EXPECT_STREQ(except_str.c_str(),my_ralph->display().c_str()) << "FAIL: Mallard display function" ;
}
#endif
