/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/Duck.h"
//#include <iostream>
#include <string.h>

#ifdef FEEDBACK_TEST_07
// Initial Test for Rubber Duck.  YayYay
TEST(RubberDuckTest,Constructor){
  Duck* my_ralph = new RubberDuck();
  QuackBehavior* m = new Mute();
  FlyBehavior* f = new FlyWithWings();
  string except_fly_perform_str="Cannot fly.";
  string except_quack_perform_str = "Quack at 2 decibels.";
  string except_fly_set_str="Fly with wings at speed of 5 mph.";
  string except_quack_set_str = "Cannot talk.";

  EXPECT_STREQ( except_fly_perform_str.c_str(),my_ralph->performFly().c_str()) << "FAIL: RubberDuck performFly function" ;
  EXPECT_STREQ( except_quack_perform_str.c_str(),my_ralph->performQuack().c_str()) << "FAIL: RubberDuck performQuack function" ;
  my_ralph->setFlyBehavior(f);
  my_ralph->setQuackBehavior(m);
  EXPECT_STREQ( except_fly_set_str.c_str(),my_ralph->performFly().c_str()) << "FAIL: RubberDuck: Duck setFly function" ;
  EXPECT_STREQ( except_quack_set_str.c_str(),my_ralph->performQuack().c_str()) << "FAIL: RubberDuck: Duck  setquack function" ;
}


TEST(RubberDuckTest,display){
  Duck* my_ralph = new RubberDuck();
  string except_str="I am a Rubber Duck.";
  EXPECT_STREQ(except_str.c_str(),my_ralph->display().c_str()) << "FAIL: RubberDuck display function" ;
}
#endif
