/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/QuackBehavior.h"
#include <string.h>

#ifdef FEEDBACK_TEST_04

TEST(SqueakTest, Constructor) {
  Squeak my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(),my_quack.quack().c_str())<<"FAIL:Squeak Constructor!";
}
TEST(SqueakTest, quack) {
  Squeak my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(),my_quack.quack().c_str())<<"FAIL:Squeak quack function!";
}

#endif
