# Simply run the compilation command so you don't have to keep typing it in

EXEC = ../Ballot_Generator
all:
	g++ -Wall -std=c++14 -static -static-libgcc -static-libstdc++ ballot_generator.cpp -o $(EXEC)

clean:
	rm -rf $(EXEC)
